# Generated by Django 5.2.6 on 2025-09-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_integrantedetalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntegranteDetalle',
            new_name='AcuerdoDirectivo',
        ),
    ]
