# Generated by Django 5.2.6 on 2025-09-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_rename_integrantedetalle_acuerdodirectivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcuerdoDirectivo',
            new_name='AcuerdoDirectiva',
        ),
        migrations.RenameModel(
            old_name='AcuerdoDetalle',
            new_name='AcuerdoOperativa',
        ),
        migrations.AlterModelOptions(
            name='acuerdodirectiva',
            options={'ordering': ['numerador']},
        ),
        migrations.AlterModelOptions(
            name='acuerdooperativa',
            options={'ordering': ['numerador']},
        ),
        migrations.AlterModelTable(
            name='acuerdodirectiva',
            table='acuerdos_directiva',
        ),
        migrations.AlterModelTable(
            name='acuerdooperativa',
            table='acuerdos_operativa',
        ),
        migrations.AlterModelTable(
            name='integrante',
            table='integrantes',
        ),
    ]
